### ISSUE TITLE
The "extend" syntax is not recognized

### ISSUE THREAD

**Issue by abompard** [lesscpy/lesscpy#43]
Less CSS has an <a href="http://lesscss.org/features/#extend-feature">"extend" feature</a> which is not recognized by lesscpy. Example with a file called "test.less" and containing:

``` css
.a {
    color: blue;
}
.b:extend(.a) {
    border: 1px;
}
```

Compiling with the original LESS compiler:

``` sh
$ lessc test.less 
.a,
.b {
  color: blue;
}
.b {
  border: 1px;
}
```

And now with lesscpy:

``` sh
$ lesscpy -V -D test.less 
Compiling target: test.less
E: test.less line: 4, Syntax Error, token: `css_class`, `.a`
```
