### ISSUE TITLE
Custom elements are not supported

### ISSUE THREAD

**Issue by dsbaars** [lesscpy/lesscpy#72]
Among others, Angular and Polymer allow you to define custom elements.
This is not supported with lesscpy

example code:
```LESS
customtag .values {
    list-style: none;
}
```

More info:
- Angular: https://docs.angularjs.org/guide/directive
- Polymer custom elements: https://customelements.io/
