### ISSUE TITLE
A lot of attributes (especially prefixed) are not supported

### ISSUE THREAD

**Issue by dsbaars** [lesscpy/lesscpy#73]
vendor-prefixed attributes and CSS 3 attributes are not supported

Test code:
```LESS
@media all and (transform-3d), (-webkit-transform-3d) {
  .carousel-inner > .item {
    -webkit-transition: -webkit-transform .6s ease-in-out;
         -o-transition:      -o-transform .6s ease-in-out;
            transition:         transform .6s ease-in-out;

    -webkit-backface-visibility: hidden;
            backface-visibility: hidden;
    -webkit-perspective: 1000;
            perspective: 1000;
  }
[...]
```

Related to #69
