### ISSUE TITLE
Raw strings incorrectly supported

### ISSUE THREAD

**Issue by njoyard** [lesscpy/lesscpy#84]
Using lesscpy version 0.11.1

Example input A:
```less
a {
  filter: ~"grayscale(1)";
}
b {
  filter: grayscale(1);
}
```
Expected output:
```css
a {
  filter: grayscale(1);
}
b {
  filter: #010101;
}
```
Actual output:
```css
a {
  filter: #010101;
}
b {
  filter: #010101;
}
```
Example B:
```less
a {
  width: calc(100px + 100px);
  height: calc(~"100px +" 100px);
}
```
Expected output:
```css
a {
  width: calc(200px);
  height: calc(100px + 100px);
}
```
Actual output:
```
E: test.less line: 3, Syntax Error, token: `t_eclose`, `"`
```
