### ISSUE TITLE
Global variables take precedence over mixin arguments

### ISSUE THREAD

**Issue by snoack** [lesscpy/lesscpy#92]
Following less code...

```less
@color: #000;

.mixin(@color) {
  color: @color;
}

.foo {
  .mixin(#ccc);
}
```

produces following CSS using `lesscpy`:

```css
.foo {
  color: #000000;
}
```

While the original `lessc` gives following output:

```css
.foo {
  color: #cccccc;
}
```

This bug also causes wrong output when building Bootstrap.
